dynamic_linkage = [
    "vnd/raylib/lib/libraylib.so.550"
]

include_paths = [
    "vnd/raylib/include"
]

sources = [
    "main",

    "man/core",
    "man/time",
    "man/str_colour",

    "man/render/renderer",
    "man/render/renderable",

    "man/things/things",
    "man/things/thing",
    "man/things/sprite",
    "man/things/spatial",
    "man/things/body",

    "game/game"
]