dynamic_linkage = [
    "vnd/raylib/lib/libraylib.so.550"
]

include_paths = [
    "vnd/raylib/include"
]

sources = [
    "main",

    "man/core",
    "man/time",
    "man/str_colour",

    "man/render/renderer_pub",
    "man/render/renderer_priv",
    "man/render/ui_renderable",

    "man/things/things",
    "man/things/thing",
    "man/things/sprite",
    "man/things/spatial",
    "man/things/body",
    "man/things/renderable",

    "man/things/ui/ui_element",
    "man/things/ui/ui_sprite",

    "game/game",
    "game/player",
    "game/room",
    "game/debug_fp_cam",
    "game/npc",
    "game/modell"
]